### ISSUE TITLE
Cant Run pip install -r requirements.txt

### ISSUE THREAD

**Issue by AJFortin** [uezo/aiavatarkit#60]
I am getting this error 

" >pip install -r requirements.txt
Requirement already satisfied: aiohttp==3.9.3 in c:\users\cidco\downloads\aiavatarkit-main\venv\lib\site-packages (from -r requirements.txt (line 1)) (3.9.3)
Collecting numpy==1.24.3 (from -r requirements.txt (line 2))
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "C:\Users\cidco\Downloads\aiavatarkit-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\cidco\Downloads\aiavatarkit-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\cidco\Downloads\aiavatarkit-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
        File "C:\Users\cidco\Downloads\aiavatarkit-main\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
        File "C:\Users\cidco\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py", line 88, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\cidco\AppData\Local\Temp\pip-build-env-1qo7cs58\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\cidco\AppData\Local\Temp\pip-build-env-1qo7cs58\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\cidco\AppData\Local\Temp\pip-build-env-1qo7cs58\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip. "

and when i did a search it came up with this

" This error occurs because pkgutil.ImpImporter has been deprecated and removed in Python 3.12. The correct attribute to use is zipimporter. "

**Comment by uezo** [comment]
Hi @AJFortin ,
Use Python 3.11 or earlier.

**Comment by AJFortin** [comment]
ok i will try that

**Comment by AJFortin** [comment]
will that interfere with my other python scripts?

**Comment by AJFortin** [comment]
Good Afternoon Uezo, does this script do anything for avatars? when i try to run it, it tells me i need a speech-to-text api
